### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by drivve92** [SoddenFilly/YCBA#3]
Hi, tell me how to run the program

**Comment by SoddenFilly** [comment]
> Hi, tell me how to run the program

Hi! Let me first off say that the program is not finished, and I recently took a break from it as I hit a massive roadblock, but I am determined to finish this.
With that outta the way - This is built to be run as a stand alone .exe file, to run the latest barely functional version go from
root>YCBA>Y.C.B.A.exe
Run this, and remember to not remove the exe from that folder otherwise it wont work.
Thank you for your interest, may I ask what lead you to this repo?
